### ISSUE TITLE
Support for compiling standard libraries without importing standard libraries

### ISSUE THREAD

**Issue by TobiasWrigstad** [parapluu/encore#404]
Compiling the _prelude_ bundle(s) (currently just the `String.enc` bundle) is not possible in isolation because the compiler automatically includes the prelude functions in every build.  This makes developing the prelude tricky. 

Fix is probably easy – a new flag and avoiding the include the prelude bundles if the flag is set.

**Comment by supercooldave** [comment]
Fixed in #788.
