### ISSUE TITLE
Deadlocking programs terminates normaly with no error message

### ISSUE THREAD

**Issue by helanhalvan** [parapluu/encore#631]
For complete code, look at my git repo, https://github.com/helanhalvan/backup/commit/feaefacbbbe33e30bd83e935dd488457766f29cf. 

Looking at my `main()` and `loop(...)`
```
class Main {
   def main() : void {
       let
       superbox = new Top_box(this.parse_file("scenario.xml"))
        x_size=0
        y_size=0
        aui=true
        sdl_main = null : SDL_Main
       in {
        print("constructor-done!\n");
       this!loop(superbox,0,aui,sdl_main);
       } 
   }
   def loop(superbox:Top_box, tick:int, ui:bool,sdl_main:SDL_Main) : void {
       print("tick {}\n",tick);
        get(superbox.move());
        this!loop(superbox,tick+1,ui,sdl_main)
       }
```
This code should trivially not terminate, as there is no branching around the call `this!loop(..)`, at least not to my understanding. Commenting out `get(supderbox.move());` will cause the program to run forever, but leaving it in will cause it to terminate normally after printing `tick 0`. 

I don't know why this is happening, but think it's related to future chaining somehow, but can't reproduce the issue. Currently it's mostly something that seems very strange, but not really anything I'm stuck on. 

Interestingly, it seems like adding a printout after `this!loop(..` does never get printed either.

**Comment by supercooldave** [comment]
Duplicates #104.
