### ISSUE TITLE
Syntax style inconsistency

### ISSUE THREAD

**Issue by supercooldave** [parapluu/encore#782]
Task creation has syntax

> async { expr }

Nowhere else in the language are squiggly parentheses used. 

Does it make sense to change this before we become too task-oriented?

**Comment by EliasC** [comment]
But you can also write it like this, no?
```
async
  expr
end
```

**Comment by EliasC** [comment]
Squiggly parentheses can be used for single line blocks elsewhere as well:
```
    if true then
      {println("foo"); println("bar")}
    end
```
I don't think there are any inconsistencies here.

**Comment by supercooldave** [comment]
My bad. I thought they were eliminated.
I'll deissue this.
