### ISSUE TITLE
Array access operator applied to string results in internal compiler error

### ISSUE THREAD

**Issue by supercooldave** [parapluu/encore#823]
Compiling the following class
```
active class Main
  def main() : unit
    val str = "foo"
    str(0)
  end 
end
```
results in the internal error
> encorec: No match in record selector argTypes

I suspect this is due to trying to use array access `(0)` on the string.
(It would be nice to use `str(n)` to access elements of the string.)

**Comment by TobiasWrigstad** [comment]
Notably, strings are not arrays. They are objects. Eventually, strings should and will support this operations if we chose to go ahead with RFC #591.

**Comment by supercooldave** [comment]
Parsing strings is hard. But I now see that I can convert a string into an array of chars.

**Comment by TobiasWrigstad** [comment]
(Obviously, this has nothing to do with your compiler error which is weird.)
