### ISSUE TITLE
printing Nothing crashes the compiler

### ISSUE THREAD

**Issue by kikofernandez** [parapluu/encore#836]
Printing `Nothing` crashes the compiler. I believe this used to **not** be the case before.

Example:

```ruby
active class Main
  def main(): unit
    println(Nothing)
  end
end
```

Output:

```
encorec test.enc --run
encorec: I don't know how to translate Bottom to pony.c
```

**Comment by supercooldave** [comment]
This is related to the new "return type" PR. I've seen the error in other situations.

**Comment by supercooldave** [comment]
Specifically, the compiler cannot work out the type of `Nothing`. Previously, this would be caught by the type checker and the programmer would be forced to put in type information. With the more relaxed type checker, the `Bottom` type propagates into the code generator, but it doesn't know how to deal with it.

My understanding is that **any** type could be used in this situation and code generation would succeed.
